# Generated by Django 3.2.12 on 2022-08-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_userextensions_userextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='facebook',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userextension',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users'),
        ),
        migrations.AddField(
            model_name='userextension',
            name='twitter',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userextension',
            name='website',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
