# Generated by Django 3.2.12 on 2022-08-19 14:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220818_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
