# Generated by Django 3.2.12 on 2022-09-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220829_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='district',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='zipcode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
