# Generated by Django 3.2.12 on 2022-09-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220906_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='district',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
