# Generated by Django 3.2.12 on 2022-09-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userextension_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='website',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
    ]
