# Generated by Django 3.2.12 on 2022-10-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20221003_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='creator',
            new_name='owner',
        ),
    ]
