# Generated by Django 3.2.12 on 2022-10-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, default=' - Not member of a team', max_length=64, null=True),
        ),
    ]
