# Generated by Django 3.0.5 on 2022-02-20 02:10

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendees',
            new_name='Attendee',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='attendees',
            new_name='attendee',
        ),
    ]
