# Generated by Django 3.2.12 on 2022-09-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20220906_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='district',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
