# Generated by Django 3.2.12 on 2022-09-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20220906_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='district1',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='zipcode1',
            new_name='zipcode',
        ),
    ]
