

category_choices = (
    ("", "All"),
    ("1", "One"),
    ("2", "Two"),
    ("3", "Three"),
    ("4", "Four"),
    ("5", "Five"),)

status = (
    ('Introduced','Introduced',),
    ('Floor Consideration','Floor Consideration',),
    ('Failed One Chamber','Failed One Chamber',),
    ('Passed One Chamber','Passed One Chamber',),
    ('Passed Both Chambers','Passed Both Chambers',),
    ('Resolving Differences','Resolving Differences',),
    ('To President','To President',),
    ('Became Law','Became Law',),
)

# Policy Areas https://www.congress.gov/help/field-values/policy-area
billPolicyArea = (
    ("", "All"),
    ("Agriculture and Food", "Agriculture and Food"),
    ("Animals", "Animals"),
    ("Armed Forces and National Security", "Armed Forces and National Security"),
    ("Arts, Culture, Religion", "Arts, Culture, Religion"),
    ("Civil Rights and Liberties, Minority Issues", "Civil Rights and Liberties, Minority Issues"),
    ("Commerce", "Commerce"),
    ("Congress", "Congress"),
    ("Crime and Law Enforcement	", "Crime and Law Enforcement	"),
    ("Economics and Public Finance	", "Economics and Public Finance	"),
    ("Education", "Education"),
    ("Emergency Management", "Emergency Management"),
    ("Energy", "Energy"),
    ("Environmental Protection", "Environmental Protection"),
    ("Families", "Families"),
    ("Finance and Financial Sector", "Finance and Financial Sector"),
    ("Foreign Trade and International Finance", "Foreign Trade and International Finance"),
    ("Government Operations and Politics", "Government Operations and Politics"),
    ("Health", "Health"),
    ("Housing and Community Development", "Housing and Community Development"),
    ("Immigration", "Immigration"),
    ("International Affairs", "International Affairs"),
    ("Labor and Employment", "Labor and Employment"),
    ("Law", "Law"),
    ("Native Americans", "Native Americans"),
    ("Public Lands and Natural Resources", "Public Lands and Natural Resources"),
    ("Science, Technology, Communications", "Science, Technology, Communications"),
    ("Social Sciences and History", "Social Sciences and History"),
    ("Social Welfare", "Social Welfare"),
    ("Sports and Recreation", "Sports and Recreation"),
    ("Taxation", "Taxation"),
    ("Transportation and Public Works", "Transportation and Public Works"),
    ("Water Resources Development", "Water Resources Development"),)

committee = (
    ("", "All"),
    ("Energy and Commerce", "Energy and Commerce"),
    ("Transportation and Infrastructure", "Transportation and Infrastructure"),
    ("Judiciary","Judiciary"),
    ("Ways and Means","Ways and Means",),
    ("Oversight and Reform","Oversight and Reform",),
    ("Education and Labor","Education and Labor",),
    ("Foreign Affairs","Foreign Affairs",),
    ("Natural Resources","Natural Resources",),
    ("Financial Services","Financial Services",),
    ("Armed Services","Armed Services",),
    ("Veterans' Affairs","Veterans' Affairs",),
    ("Agriculture","Agriculture",),
    ("House Administration","House Administration",),
    ("Rules","Rules",),
    ("Homeland Security","Homeland Security",),
    ("Science, Space, and Technology","Science, Space, and Technology",),
    ("Appropriations","Appropriations",),
    ("Small Business","Small Business",),
    ("Budget","Budget",),
    ("Intelligence","Intelligence",),
    ("Ethics","Ethics",),
    ("Select Committee on the Climate Crisis","Select Committee on the Climate Crisis",),
    ("Select Committee on the Modernization of Congress","Select Committee on the Modernization of Congress",),
    ("Select Committee on Economic Disparity and Fairness in Growth","Select Committee on Economic Disparity and Fairness in Growth",),
    ("Select Investigate the January 6th Attack on the United States Capitol","Select Investigate the January 6th Attack on the United States Capitol",),
    ("Energy","Energy",),
    ("Whole House on State of Union","Whole House on State of Union",),)

# Legislative Subject Terms https://www.congress.gov/help/field-values/legislative-subject-terms
billSubjectTerm = (
    ("", "All"),
    ("Abortion", "Abortion"),
    ("Academic performance and assessments", "Academic performance and assessments"),
    ("Accidents", "Accidents"),
    ("Accounting and auditing", "Accounting and auditing"),
    ("Administrative law and regulatory procedures", "Administrative law and regulatory procedures"),
    ("Administrative remedies", "Administrative remedies"),
    ("Adoption and foster care", "Adoption and foster care"),
    ("Adult day care", "Adult day care"),
    ("Adult education and literacy", "Adult education and literacy"),
    ("Advanced technology and technological innovations", "Advanced technology and technological innovations"),
    ("Advisory bodies", "Advisory bodies"),
    ("Age discrimination", "Age discrimination"),
    ("Aging", "Aging"),
    ("Agricultural conservation and pollution", "Agricultural conservation and pollution"),
    ("Agricultural education", "Agricultural education"),
    ("Agricultural equipment and machinery", "Agricultural equipment and machinery"),
    ("Agricultural insurance", "Agricultural insurance"),
    ("Agricultural marketing and promotion", "Agricultural marketing and promotion"),
    ("Agricultural practices and innovations", "Agricultural practices and innovations"),
    ("Agricultural prices, subsidies, credit", "Agricultural prices, subsidies, credit"),
    ("Agricultural research", "Agricultural research"),
    ("Agricultural trade", "Agricultural trade"),
    ("Air quality", "Air quality"),
    ("Alaska Natives and Hawaiians", "Alaska Natives and Hawaiians"),
    ("Alcoholic beverages", "Alcoholic beverages"),
    ("Allergies", "Allergies"),
    ("Alliances", "Alliances"),
    ("Allied health services", "Allied health services"),
    ("Alternative and renewable resources", "Alternative and renewable resources"),
    ("Alternative dispute resolution, mediation, arbitration", "Alternative dispute resolution, mediation, arbitration"),
    ("Alternative treatments", "Alternative treatments"),
    ("Animal and plant health", "Animal and plant health"),
    ("Animal protection and human-animal relationships", "Animal protection and human-animal relationships"),
    ("Appropriations", "Appropriations"),
    ("Aquaculture", "Aquaculture"),
    ("Aquatic ecology", "Aquatic ecology"),
    ("Arab-Israeli relations", "Arab-Israeli relations"),
    ("Archaeology and anthropology", "Archaeology and anthropology"),
    ("Architecture", "Architecture"),
    ("Arctic and polar regions", "Arctic and polar regions"),
    ("Area studies and international education", "Area studies and international education"),
    ("Arms control and nonproliferation", "Arms control and nonproliferation"),
    ("Art, artists, authorship", "Art, artists, authorship"),
    ("Assault and harassment offenses", "Assault and harassment offenses"),
    ("Astronomy", "Astronomy"),
    ("Athletes", "Athletes"),
    ("Atmospheric science and weather", "Atmospheric science and weather"),
    ("Aviation and airports", "Aviation and airports"),
    ("Bank accounts, deposits, capital", "Bank accounts, deposits, capital"),
    ("Banking and financial institutions regulation", "Banking and financial institutions regulation"),
    ("Bankruptcy", "Bankruptcy"),
    ("Behavioral sciences", "Behavioral sciences"),
    ("Biological and life sciences", "Biological and life sciences"),
    ("Birds", "Birds"),
    ("Birth defects", "Birth defects"),
    ("Blood and blood diseases", "Blood and blood diseases"),
    ("Books and print media", "Books and print media"),
    ("Border security and unlawful immigration", "Border security and unlawful immigration"),
    ("Broadcasting, cable, digital technologies", "Broadcasting, cable, digital technologies"),
    ("Budget deficits and national debt", "Budget deficits and national debt"),
    ("Budget process", "Budget process"),
    ("Building construction", "Building construction"),
    ("Business education", "Business education"),
    ("Business ethics", "Business ethics"),
    ("Business expenses", "Business expenses"),
    ("Business investment and capital", "Business investment and capital"),
    ("Business records", "Business records"),
    ("Buy American requirements", "Buy American requirements"),
    ("Cancer", "Cancer"),
    ("Capital gains tax", "Capital gains tax"),
    ("Cardiovascular and respiratory health", "Cardiovascular and respiratory health"),
    ("Cell biology and embryology", "Cell biology and embryology"),
    ("Cemeteries and funerals", "Cemeteries and funerals"),
    ("Census and government statistics", "Census and government statistics"),
    ("Charitable contributions", "Charitable contributions"),
    ("Chemical and biological weapons", "Chemical and biological weapons"),
    ("Chemistry", "Chemistry"),
    ("Child care and development", "Child care and development"),
    ("Child health", "Child health"),
    ("Child safety and welfare", "Child safety and welfare"),
    ("Citizenship and naturalization", "Citizenship and naturalization"),
    ("Civics education", "Civics education"),
    ("Civil actions and liability", "Civil actions and liability"),
    ("Civil disturbances", "Civil disturbances"),
    ("Climate change and greenhouse gases", "Climate change and greenhouse gases"),
    ("Coal", "Coal"),
    ("Coast guard", "Coast guard"),
    ("Collective security", "Collective security"),
    ("Commemorative events and holidays", "Commemorative events and holidays"),
    ("Commodities markets", "Commodities markets"),
    ("Community life and organization", "Community life and organization"),
    ("Commuting", "Commuting"),
    ("Competition and antitrust", "Competition and antitrust"),
    ("Competitiveness, trade promotion, trade deficits", "Competitiveness, trade promotion, trade deficits"),
    ("Comprehensive health care", "Comprehensive health care"),
    ("Computer security and identity theft", "Computer security and identity theft"),
    ("Computers and information technology", "Computers and information technology"),
    ("Conflicts and wars", "Conflicts and wars"),
    ("Congressional agencies", "Congressional agencies"),
    ("Congressional committees", "Congressional committees"),
    ("Congressional districts and representation", "Congressional districts and representation"),
    ("Congressional elections", "Congressional elections"),
    ("Congressional leadership", "Congressional leadership"),
    ("Congressional officers and employees", "Congressional officers and employees"),
    ("Congressional operations and organization", "Congressional operations and organization"),
    ("Congressional oversight", "Congressional oversight"),
    ("Congressional tributes", "Congressional tributes"),
    ("Congressional-executive branch relations", "Congressional-executive branch relations"),
    ("Constitution and constitutional amendments", "Constitution and constitutional amendments"),
    ("Consumer affairs", "Consumer affairs"),
    ("Consumer credit", "Consumer credit"),
    ("Contracts and agency", "Contracts and agency"),
    ("Cooperative and condominium housing", "Cooperative and condominium housing"),
    ("Corporate finance and management", "Corporate finance and management"),
    ("Correctional facilities and imprisonment", "Correctional facilities and imprisonment"),
    ("Cosmetics and personal care", "Cosmetics and personal care"),
    ("Credit and credit markets", "Credit and credit markets"),
    ("Crime prevention", "Crime prevention"),
    ("Crime victims", "Crime victims"),
    ("Crimes against animals and natural resources", "Crimes against animals and natural resources"),
    ("Crimes against children", "Crimes against children"),
    ("Crimes against property", "Crimes against property"),
    ("Crimes against women", "Crimes against women"),
    ("Criminal investigation, prosecution, interrogation", "Criminal investigation, prosecution, interrogation"),
    ("Criminal justice information and records", "Criminal justice information and records"),
    ("Criminal procedure and sentencing", "Criminal procedure and sentencing"),
    ("Cultural exchanges and relations", "Cultural exchanges and relations"),
    ("Currency", "Currency"),
    ("Customs enforcement", "Customs enforcement"),
    ("Dams and canals", "Dams and canals"),
    ("Debt collection", "Debt collection"),
    ("Defense spending", "Defense spending"),
    ("Dental care", "Dental care"),
    ("Detention of persons", "Detention of persons"),
    ("Digestive and metabolic diseases", "Digestive and metabolic diseases"),
    ("Digital media", "Digital media"),
    ("Diplomacy, foreign officials, Americans abroad", "Diplomacy, foreign officials, Americans abroad"),
    ("Disability and health-based discrimination", "Disability and health-based discrimination"),
    ("Disability and paralysis", "Disability and paralysis"),
    ("Disability assistance", "Disability assistance"),
    ("Disaster relief and insurance", "Disaster relief and insurance"),
    ("Domestic violence and child abuse", "Domestic violence and child abuse"),
    ("Drug safety, medical device, and laboratory regulation", "Drug safety, medical device, and laboratory regulation"),
    ("Drug therapy", "Drug therapy"),
    ("Drug trafficking and controlled substances", "Drug trafficking and controlled substances"),
    ("Drug, alcohol, tobacco use", "Drug, alcohol, tobacco use"),
    ("Due process and equal protection", "Due process and equal protection"),
    ("Earth sciences", "Earth sciences"),
    ("Ecology", "Ecology"),
    ("Economic development", "Economic development"),
    ("Economic performance and conditions", "Economic performance and conditions"),
    ("Economic theory", "Economic theory"),
    ("Education of the disadvantaged", "Education of the disadvantaged"),
    ("Education programs funding", "Education programs funding"),
    ("Educational facilities and institutions", "Educational facilities and institutions"),
    ("Educational guidance", "Educational guidance"),
    ("Educational technology and distance education", "Educational technology and distance education"),
    ("Elections, voting, political campaign regulation", "Elections, voting, political campaign regulation"),
    ("Electric power generation and transmission", "Electric power generation and transmission"),
    ("Elementary and secondary education", "Elementary and secondary education"),
    ("Emergency communications systems", "Emergency communications systems"),
    ("Emergency medical services and trauma care", "Emergency medical services and trauma care"),
    ("Emergency planning and evacuation", "Emergency planning and evacuation"),
    ("Employee benefits and pensions", "Employee benefits and pensions"),
    ("Employee hiring", "Employee hiring"),
    ("Employee leave", "Employee leave"),
    ("Employee performance", "Employee performance"),
    ("Employment and training programs", "Employment and training programs"),
    ("Employment discrimination and employee rights", "Employment discrimination and employee rights"),
    ("Employment taxes", "Employment taxes"),
    ("Endangered and threatened species", "Endangered and threatened species"),
    ("Energy assistance for the poor and aged", "Energy assistance for the poor and aged"),
    ("Energy efficiency and conservation", "Energy efficiency and conservation"),
    ("Energy prices", "Energy prices"),
    ("Energy research", "Energy research"),
    ("Energy revenues and royalties", "Energy revenues and royalties"),
    ("Energy storage, supplies, demand", "Energy storage, supplies, demand"),
    ("Environmental assessment, monitoring, research", "Environmental assessment, monitoring, research"),
    ("Environmental education", "Environmental education"),
    ("Environmental health", "Environmental health"),
    ("Environmental regulatory procedures", "Environmental regulatory procedures"),
    ("Environmental technology", "Environmental technology"),
    ("Espionage and treason", "Espionage and treason"),
    ("Ethnic studies", "Ethnic studies"),
    ("Evidence and witnesses", "Evidence and witnesses"),
    ("Executive agency funding and structure", "Executive agency funding and structure"),
    ("Family planning and birth control", "Family planning and birth control"),
    ("Family relationships", "Family relationships"),
    ("Family services", "Family services"),
    ("Farmland", "Farmland"),
    ("Federal appellate courts", "Federal appellate courts"),
    ("Federal district courts", "Federal district courts"),
    ("Federal officials", "Federal officials"),
    ("Federal preemption", "Federal preemption"),
    ("Federal-Indian relations", "Federal-Indian relations"),
    ("Federally chartered organizations", "Federally chartered organizations"),
    ("Financial crises and stabilization", "Financial crises and stabilization"),
    ("Financial literacy", "Financial literacy"),
    ("Financial services and investments", "Financial services and investments"),
    ("Firearms and explosives", "Firearms and explosives"),
    ("Fires", "Fires"),
    ("First Amendment rights", "First Amendment rights"),
    ("First responders and emergency personnel", "First responders and emergency personnel"),
    ("Fishes", "Fishes"),
    ("Floods and storm protection", "Floods and storm protection"),
    ("Food assistance and relief", "Food assistance and relief"),
    ("Food industry and services", "Food industry and services"),
    ("Food supply, safety, and labeling", "Food supply, safety, and labeling"),
    ("Foreign aid and international relief", "Foreign aid and international relief"),
    ("Foreign and international banking", "Foreign and international banking"),
    ("Foreign and international corporations", "Foreign and international corporations"),
    ("Foreign labor", "Foreign labor"),
    ("Foreign language and bilingual programs", "Foreign language and bilingual programs"),
    ("Foreign loans and debt", "Foreign loans and debt"),
    ("Foreign property", "Foreign property"),
    ("Forests, forestry, trees", "Forests, forestry, trees"),
    ("Fraud offenses and financial crimes", "Fraud offenses and financial crimes"),
    ("Free trade and trade barriers", "Free trade and trade barriers"),
    ("Freedom of information", "Freedom of information"),
    ("Fruit and vegetables", "Fruit and vegetables"),
    ("Gambling", "Gambling"),
    ("Games and hobbies", "Games and hobbies"),
    ("General Native American affairs matters", "General Native American affairs matters"),
    ("General agriculture matters", "General agriculture matters"),
    ("General business and commerce matters", "General business and commerce matters"),
    ("General education matters", "General education matters"),
    ("General energy matters", "General energy matters"),
    ("General foreign operations matters", "General foreign operations matters"),
    ("General health and health care finance matters", "General health and health care finance matters"),
    ("General public lands matters", "General public lands matters"),
    ("General science and technology matters", "General science and technology matters"),
    ("General taxation matters", "General taxation matters"),
    ("Genetics", "Genetics"),
    ("Geography and mapping", "Geography and mapping"),
    ("Government buildings, facilities, and property", "Government buildings, facilities, and property"),
    ("Government corporations and government-sponsored enterprises", "Government corporations and government-sponsored enterprises"),
    ("Government employee pay, benefits, personnel management", "Government employee pay, benefits, personnel management"),
    ("Government ethics and transparency, public corruption", "Government ethics and transparency, public corruption"),
    ("Government information and archives", "Government information and archives"),
    ("Government lending and loan guarantees", "Government lending and loan guarantees"),
    ("Government liability", "Government liability"),
    ("Government studies and investigations", "Government studies and investigations"),
    ("Government trust funds", "Government trust funds"),
    ("Grain", "Grain"),
    ("HIV/AIDS", "HIV/AIDS"),
    ("Hate crimes", "Hate crimes"),
    ("Hazardous wastes and toxic substances", "Hazardous wastes and toxic substances"),
    ("Health care costs and insurance", "Health care costs and insurance"),
    ("Health care coverage and access", "Health care coverage and access"),
    ("Health care quality", "Health care quality"),
    ("Health facilities and institutions", "Health facilities and institutions"),
    ("Health information and medical records", "Health information and medical records"),
    ("Health personnel", "Health personnel"),
    ("Health programs administration and funding", "Health programs administration and funding"),
    ("Health promotion and preventive care", "Health promotion and preventive care"),
    ("Health technology, devices, supplies", "Health technology, devices, supplies"),
    ("Hearing, speech, and vision care", "Hearing, speech, and vision care"),
    ("Hereditary and development disorders", "Hereditary and development disorders"),
    ("Higher education", "Higher education"),
    ("Historic sites and heritage areas", "Historic sites and heritage areas"),
    ("Historical and cultural resources", "Historical and cultural resources"),
    ("Home and outpatient care", "Home and outpatient care"),
    ("Homeland security", "Homeland security"),
    ("Homelessness and emergency shelter", "Homelessness and emergency shelter"),
    ("Horticulture and plants", "Horticulture and plants"),
    ("Hospital care", "Hospital care"),
    ("House of Representatives", "House of Representatives"),
    ("Housing and community development funding", "Housing and community development funding"),
    ("Housing discrimination", "Housing discrimination"),
    ("Housing finance and home ownership", "Housing finance and home ownership"),
    ("Housing for the elderly and disabled", "Housing for the elderly and disabled"),
    ("Housing industry and standards", "Housing industry and standards"),
    ("Housing supply and affordability", "Housing supply and affordability"),
    ("Human rights", "Human rights"),
    ("Human trafficking", "Human trafficking"),
    ("Humanities programs funding", "Humanities programs funding"),
    ("Hunting and fishing", "Hunting and fishing"),
    ("Hybrid, electric, and advanced technology vehicles", "Hybrid, electric, and advanced technology vehicles"),
    ("Hydrology and hydrography", "Hydrology and hydrography"),
    ("Immigrant health and welfare", "Immigrant health and welfare"),
    ("Immigration status and procedures", "Immigration status and procedures"),
    ("Immunology and vaccination", "Immunology and vaccination"),
    ("Income tax credits", "Income tax credits"),
    ("Income tax deductions", "Income tax deductions"),
    ("Income tax deferral", "Income tax deferral"),
    ("Income tax exclusion", "Income tax exclusion"),
    ("Income tax rates", "Income tax rates"),
    ("Indian claims", "Indian claims"),
    ("Indian lands and resources rights", "Indian lands and resources rights"),
    ("Indian social and development programs", "Indian social and development programs"),
    ("Industrial facilities", "Industrial facilities"),
    ("Industrial policy and productivity", "Industrial policy and productivity"),
    ("Infectious and parasitic diseases", "Infectious and parasitic diseases"),
    ("Inflation and prices", "Inflation and prices"),
    ("Infrastructure development", "Infrastructure development"),
    ("Insects", "Insects"),
    ("Insurance industry and regulation", "Insurance industry and regulation"),
    ("Intellectual property", "Intellectual property"),
    ("Intelligence activities, surveillance, classified information", "Intelligence activities, surveillance, classified information"),
    ("Interest, dividends, interest rates", "Interest, dividends, interest rates"),
    ("Intergovernmental relations", "Intergovernmental relations"),
    ("International exchange and broadcasting", "International exchange and broadcasting"),
    ("International law and treaties", "International law and treaties"),
    ("International monetary system and foreign exchange", "International monetary system and foreign exchange"),
    ("International organizations and cooperation", "International organizations and cooperation"),
    ("International scientific cooperation", "International scientific cooperation"),
    ("Internet, web applications, social media", "Internet, web applications, social media"),
    ("Judges", "Judges"),
    ("Judicial procedure and administration", "Judicial procedure and administration"),
    ("Judicial review and appeals", "Judicial review and appeals"),
    ("Jurisdiction and venue", "Jurisdiction and venue"),
    ("Juvenile crime and gang violence", "Juvenile crime and gang violence"),
    ("Labor market", "Labor market"),
    ("Labor standards", "Labor standards"),
    ("Labor-management relations", "Labor-management relations"),
    ("Lakes and rivers", "Lakes and rivers"),
    ("Land transfers", "Land transfers"),
    ("Land use and conservation", "Land use and conservation"),
    ("Landlord and tenant", "Landlord and tenant"),
    ("Language arts", "Language arts"),
    ("Law enforcement administration and funding", "Law enforcement administration and funding"),
    ("Law enforcement officers", "Law enforcement officers"),
    ("Lawyers and legal services", "Lawyers and legal services"),
    ("Lease and rental services", "Lease and rental services"),
    ("Legal fees and court costs", "Legal fees and court costs"),
    ("Legislative rules and procedure", "Legislative rules and procedure"),
    ("Libraries and archives", "Libraries and archives"),
    ("Licensing and registrations", "Licensing and registrations"),
    ("Life, casualty, property insurance", "Life, casualty, property insurance"),
    ("Lighting, heating, cooling", "Lighting, heating, cooling"),
    ("Literature", "Literature"),
    ("Livestock", "Livestock"),
    ("Long-term, rehabilitative, and terminal care", "Long-term, rehabilitative, and terminal care"),
    ("Low- and moderate-income housing", "Low- and moderate-income housing"),
    ("Mammals", "Mammals"),
    ("Manufacturing", "Manufacturing"),
    ("Marine and coastal resources, fisheries", "Marine and coastal resources, fisheries"),
    ("Marine and inland water transportation", "Marine and inland water transportation"),
    ("Marine pollution", "Marine pollution"),
    ("Marketing and advertising", "Marketing and advertising"),
    ("Marriage and family status", "Marriage and family status"),
    ("Materials", "Materials"),
    ("Meat", "Meat"),
    ("Medicaid", "Medicaid"),
    ("Medical education", "Medical education"),
    ("Medical ethics", "Medical ethics"),
    ("Medical research", "Medical research"),
    ("Medical tests and diagnostic methods", "Medical tests and diagnostic methods"),
    ("Medicare", "Medicare"),
    ("Members of Congress", "Members of Congress"),
    ("Mental health", "Mental health"),
    ("Metals", "Metals"),
    ("Migrant, seasonal, agricultural labor", "Migrant, seasonal, agricultural labor"),
    ("Military assistance, sales, and agreements", "Military assistance, sales, and agreements"),
    ("Military civil functions", "Military civil functions"),
    ("Military command and structure", "Military command and structure"),
    ("Military education and training", "Military education and training"),
    ("Military facilities and property", "Military facilities and property"),
    ("Military history", "Military history"),
    ("Military law", "Military law"),
    ("Military medicine", "Military medicine"),
    ("Military operations and strategy", "Military operations and strategy"),
    ("Military personnel and dependents", "Military personnel and dependents"),
    ("Military procurement, research, weapons development", "Military procurement, research, weapons development"),
    ("Military readiness", "Military readiness"),
    ("Militias and paramilitary groups", "Militias and paramilitary groups"),
    ("Mining", "Mining"),
    ("Minority and disadvantaged businesses", "Minority and disadvantaged businesses"),
    ("Minority education", "Minority education"),
    ("Minority employment", "Minority employment"),
    ("Minority health", "Minority health"),
    ("Missing persons", "Missing persons"),
    ("Monetary policy", "Monetary policy"),
    ("Monuments and memorials", "Monuments and memorials"),
    ("Motor carriers", "Motor carriers"),
    ("Motor fuels", "Motor fuels"),
    ("Motor vehicles", "Motor vehicles"),
    ("Multilateral development programs", "Multilateral development programs"),
    ("Musculoskeletal and skin diseases", "Musculoskeletal and skin diseases"),
    ("Museums, exhibitions, cultural centers", "Museums, exhibitions, cultural centers"),
    ("Music", "Music"),
    ("Named Entities - Geographic", "Named Entities - Geographic"),
    ("Named Entities - Organizations", "Named Entities - Organizations"),
    ("National Guard and reserves", "National Guard and reserves"),
    ("National and community service", "National and community service"),
    ("National symbols", "National symbols"),
    ("Natural disasters", "Natural disasters"),
    ("Navigation, waterways, harbors", "Navigation, waterways, harbors"),
    ("Neurological disorders", "Neurological disorders"),
    ("News media and reporting", "News media and reporting"),
    ("Noise pollution", "Noise pollution"),
    ("Normal trade relations, most-favored-nation treatment", "Normal trade relations, most-favored-nation treatment"),
    ("Nuclear power", "Nuclear power"),
    ("Nuclear weapons", "Nuclear weapons"),
    ("Nursing", "Nursing"),
    ("Nutrition and diet", "Nutrition and diet"),
    ("Oil and gas", "Oil and gas"),
    ("Olympic games", "Olympic games"),
    ("Organ and tissue donation and transplantation", "Organ and tissue donation and transplantation"),
    ("Organized crime", "Organized crime"),
    ("Outdoor recreation", "Outdoor recreation"),
    ("Palestinians", "Palestinians"),
    ("Parks, recreation areas, trails", "Parks, recreation areas, trails"),
    ("Pedestrians and bicycling", "Pedestrians and bicycling"),
    ("Performance measurement", "Performance measurement"),
    ("Performing arts", "Performing arts"),
    ("Personnel records", "Personnel records"),
    ("Pest management", "Pest management"),
    ("Photography and imaging", "Photography and imaging"),
    ("Physical fitness and lifestyle", "Physical fitness and lifestyle"),
    ("Pipelines", "Pipelines"),
    ("Policy sciences", "Policy sciences"),
    ("Political advertising", "Political advertising"),
    ("Political movements and philosophies", "Political movements and philosophies"),
    ("Political parties and affiliation", "Political parties and affiliation"),
    ("Political representation", "Political representation"),
    ("Pollution liability", "Pollution liability"),
    ("Pornography", "Pornography"),
    ("Postal service", "Postal service"),
    ("Poverty and welfare assistance", "Poverty and welfare assistance"),
    ("Preschool education", "Preschool education"),
    ("Prescription drugs", "Prescription drugs"),
    ("Presidential administrations", "Presidential administrations"),
    ("Presidents and presidential powers, Vice Presidents", "Presidents and presidential powers, Vice Presidents"),
    ("Private Legislation", "Private Legislation"),
    ("Product development and innovation", "Product development and innovation"),
    ("Product safety and quality", "Product safety and quality"),
    ("Professional sports", "Professional sports"),
    ("Property rights", "Property rights"),
    ("Property tax", "Property tax"),
    ("Protection of officials", "Protection of officials"),
    ("Protest and dissent", "Protest and dissent"),
    ("Public contracts and procurement", "Public contracts and procurement"),
    ("Public housing", "Public housing"),
    ("Public participation and lobbying", "Public participation and lobbying"),
    ("Public transit", "Public transit"),
    ("Public utilities and utility rates", "Public utilities and utility rates"),
    ("Public-private cooperation", "Public-private cooperation"),
    ("Racial and ethnic relations", "Racial and ethnic relations"),
    ("Radiation", "Radiation"),
    ("Radio spectrum allocation", "Radio spectrum allocation"),
    ("Radioactive wastes and releases", "Radioactive wastes and releases"),
    ("Railroads", "Railroads"),
    ("Real estate business", "Real estate business"),
    ("Reconstruction and stabilization", "Reconstruction and stabilization"),
    ("Refugees, asylum, displaced persons", "Refugees, asylum, displaced persons"),
    ("Regional and metropolitan planning", "Regional and metropolitan planning"),
    ("Religion", "Religion"),
    ("Reptiles", "Reptiles"),
    ("Research administration and funding", "Research administration and funding"),
    ("Research and development", "Research and development"),
    ("Research ethics", "Research ethics"),
    ("Residential rehabilitation and home repair", "Residential rehabilitation and home repair"),
    ("Retail and wholesale trades", "Retail and wholesale trades"),
    ("Right of privacy", "Right of privacy"),
    ("Roads and highways", "Roads and highways"),
    ("Rule of law and government transparency", "Rule of law and government transparency"),
    ("Rural conditions and development", "Rural conditions and development"),
    ("Sales and excise taxes", "Sales and excise taxes"),
    ("Sanctions", "Sanctions"),
    ("School administration", "School administration"),
    ("School athletics", "School athletics"),
    ("Science and engineering education", "Science and engineering education"),
    ("Scientific communication", "Scientific communication"),
    ("Seafood", "Seafood"),
    ("Seashores and lakeshores", "Seashores and lakeshores"),
    ("Securities", "Securities"),
    ("Self-employed", "Self-employed"),
    ("Senate", "Senate"),
    ("Separation, divorce, custody, support", "Separation, divorce, custody, support"),
    ("Service animals", "Service animals"),
    ("Service industries", "Service industries"),
    ("Sex and reproductive health", "Sex and reproductive health"),
    ("Sex offenses", "Sex offenses"),
    ("Sex, gender, sexual orientation discrimination", "Sex, gender, sexual orientation discrimination"),
    ("Sexually transmitted diseases", "Sexually transmitted diseases"),
    ("Small business", "Small business"),
    ("Small towns", "Small towns"),
    ("Smuggling and trafficking", "Smuggling and trafficking"),
    ("Social security and elderly assistance", "Social security and elderly assistance"),
    ("Social work, volunteer service, charitable organizations", "Social work, volunteer service, charitable organizations"),
    ("Soil pollution", "Soil pollution"),
    ("Solid waste and recycling", "Solid waste and recycling"),
    ("Sound recording", "Sound recording"),
    ("Sovereignty, recognition, national governance and status", "Sovereignty, recognition, national governance and status"),
    ("Space flight and exploration", "Space flight and exploration"),
    ("Spacecraft and satellites", "Spacecraft and satellites"),
    ("Special education", "Special education"),
    ("Specialized courts", "Specialized courts"),
    ("Sports and recreation facilities", "Sports and recreation facilities"),
    ("State and local courts", "State and local courts"),
    ("State and local finance", "State and local finance"),
    ("State and local government operations", "State and local government operations"),
    ("State and local taxation", "State and local taxation"),
    ("Strategic materials and reserves", "Strategic materials and reserves"),
    ("Student aid and college costs", "Student aid and college costs"),
    ("Student records", "Student records"),
    ("Subversive activities", "Subversive activities"),
    ("Supreme Court", "Supreme Court"),
    ("Surgery and anesthesia", "Surgery and anesthesia"),
    ("Tariffs", "Tariffs"),
    ("Tax administration and collection, taxpayers", "Tax administration and collection, taxpayers"),
    ("Tax reform and tax simplification", "Tax reform and tax simplification"),
    ("Tax treatment of families", "Tax treatment of families"),
    ("Tax-exempt organizations", "Tax-exempt organizations"),
    ("Taxation of foreign income", "Taxation of foreign income"),
    ("Teaching, teachers, curricula", "Teaching, teachers, curricula"),
    ("Technology assessment", "Technology assessment"),
    ("Technology transfer and commercialization", "Technology transfer and commercialization"),
    ("Teenage pregnancy", "Teenage pregnancy"),
    ("Telecommunication rates and fees", "Telecommunication rates and fees"),
    ("Telephone and wireless communication", "Telephone and wireless communication"),
    ("Television and film", "Television and film"),
    ("Temporary and part-time employment", "Temporary and part-time employment"),
    ("Terrorism", "Terrorism"),
    ("Time and calendar", "Time and calendar"),
    ("Trade adjustment assistance", "Trade adjustment assistance"),
    ("Trade agreements and negotiations", "Trade agreements and negotiations"),
    ("Trade restrictions", "Trade restrictions"),
    ("Trade secrets and economic espionage", "Trade secrets and economic espionage"),
    ("Transfer and inheritance taxes", "Transfer and inheritance taxes"),
    ("Transportation costs", "Transportation costs"),
    ("Transportation employees", "Transportation employees"),
    ("Transportation programs funding", "Transportation programs funding"),
    ("Transportation safety and security", "Transportation safety and security"),
    ("Travel and tourism", "Travel and tourism"),
    ("U.S. Capitol", "U.S. Capitol"),
    ("U.S. and foreign investments", "U.S. and foreign investments"),
    ("U.S. history", "U.S. history"),
    ("U.S. territories and protectorates", "U.S. territories and protectorates"),
    ("Unemployment", "Unemployment"),
    ("Urban and suburban affairs and development", "Urban and suburban affairs and development"),
    ("User charges and fees", "User charges and fees"),
    ("Veterans' education, employment, rehabilitation", "Veterans' education, employment, rehabilitation"),
    ("Veterans' loans, housing, homeless programs", "Veterans' loans, housing, homeless programs"),
    ("Veterans' medical care", "Veterans' medical care"),
    ("Veterans' organizations and recognition", "Veterans' organizations and recognition"),
    ("Veterans' pensions and compensation", "Veterans' pensions and compensation"),
    ("Veterinary medicine and animal diseases", "Veterinary medicine and animal diseases"),
    ("Violent crime", "Violent crime"),
    ("Visas and passports", "Visas and passports"),
    ("Vocational and technical education", "Vocational and technical education"),
    ("Voting rights", "Voting rights"),
    ("Wages and earnings", "Wages and earnings"),
    ("War and emergency powers", "War and emergency powers"),
    ("War crimes, genocide, crimes against humanity", "War crimes, genocide, crimes against humanity"),
    ("Water quality", "Water quality"),
    ("Water resources funding", "Water resources funding"),
    ("Water storage", "Water storage"),
    ("Water use and supply", "Water use and supply"),
    ("Watersheds", "Watersheds"),
    ("Wetlands", "Wetlands"),
    ("White-collar crime", "White-collar crime"),
    ("Wilderness and natural areas, wildlife refuges, wild rivers, habitats", "Wilderness and natural areas, wildlife refuges, wild rivers, habitats"),
    ("Wildlife conservation and habitat protection", "Wildlife conservation and habitat protection"),
    ("Women in business", "Women in business"),
    ("Women's education", "Women's education"),
    ("Women's employment", "Women's employment"),
    ("Women's health", "Women's health"),
    ("Women's rights", "Women's rights"),
    ("Worker safety and health", "Worker safety and health"),
    ("World health", "World health"),
    ("World history", "World history"),
    ("Youth employment and child labor", "Youth employment and child labor"),)

