# Generated by Django 3.2.12 on 2022-08-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dummy',
        ),
    ]
