# Generated by Django 3.2.12 on 2022-08-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='snippet',
            new_name='excerpt',
        ),
    ]
