# Generated by Django 3.2.12 on 2022-09-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20220907_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='date',
        ),
    ]
