# Generated by Django 3.2.12 on 2022-08-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('H.R.', 'House Bill'), ('S.', 'Senate Bill'), ('H.J. Res.', 'House Joint Resolution'), ('S.J. Res.', 'Senate Joint Resolution'), ('H. Con. Res.', 'House Concurrent Resolution'), ('S. Con. Res.', 'Senate Concurrent Resolution'), ('H. Res.', 'House Simple Resolution'), ('S. Res.', 'Senate Simple Resolution')], default='H.R.', max_length=64)),
                ('number', models.IntegerField()),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('date_introduced', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('approve', 'Approve'), ('disapprove', 'Disapprove'), ('undecided', 'Undecided'), ('abstain', 'Abstain')], default='abstain', max_length=64)),
                ('count', models.IntegerField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='polls.bill')),
            ],
        ),
    ]
