# Generated by Django 3.2.12 on 2022-08-24 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['bill', 'vote']},
        ),
        migrations.AddField(
            model_name='poll',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bill',
            name='type',
            field=models.CharField(choices=[('H.R.', 'House Bill'), ('S.', 'Senate Bill'), ('H.J. Res.', 'House Joint Resolution'), ('S.J. Res.', 'Senate Joint Resolution'), ('H. Con. Res.', 'House Concurrent Resolution'), ('S. Con. Res.', 'Senate Concurrent Resolution'), ('H. Res.', 'House Simple Resolution'), ('S. Res.', 'Senate Simple Resolution')], default='H.R.', max_length=32),
        ),
    ]
