# Generated by Django 3.2.12 on 2022-08-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220824_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['bill']},
        ),
        migrations.RemoveField(
            model_name='poll',
            name='count',
        ),
    ]
