# Generated by Django 3.2.12 on 2022-09-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20220910_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
