# Generated by Django 3.2.12 on 2022-09-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_bill_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
